"""SnowballBot Built-in Skill Registry"""

from skills.council import CouncilSkill as Council

SKILL_REGISTRY = {
    "key_rotator": {
        "name": "Key Rotator",
        "description": "Smart API key rotation with circuit breaking. Rotates at 90% quota, auto-recovers after 60s.",
        "category": "infrastructure",
        "needs_config": [],
        "icon": "key",
        "agent_action": None,
    },
    "sovereign_memory": {
        "name": "Sovereign Memory",
        "description": "Blake3-sealed content-addressed memory with Gaussian relevance scoring and Merkle tree integrity proofs.",
        "category": "memory",
        "needs_config": [],
        "icon": "memory",
        "agent_action": "skill_memory",
    },
    "snowball_swarm": {
        "name": "Snowball Swarm",
        "description": "Model-agnostic parallel agent swarm — 10 predefined roles, Blake3 witness chain, no vendor lock-in.",
        "category": "agents",
        "needs_config": [],
        "icon": "swarm",
        "agent_action": "skill_swarm",
    },
    "async_messaging": {
        "name": "GutPunch Messaging",
        "description": "Proactive Telegram notifications. Three triggers: SCHEDULE, TIMED, GUTPUNCH (semantic weight threshold).",
        "category": "communication",
        "needs_config": ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"],
        "icon": "message",
        "agent_action": "skill_message",
    },
    "hobby": {
        "name": "Emergent Interests",
        "description": "Three-pass: surface interest detection → underlying pattern extraction → cross-domain discovery.",
        "category": "intelligence",
        "needs_config": [],
        "icon": "sparkle",
        "agent_action": None,
    },
    "flipbot": {
        "name": "FlipBot",
        "description": "Screenshot-to-listing arbitrage. Vision extraction + eBay comps + optimized resale listing + profit calc.",
        "category": "tools",
        "needs_config": ["EBAY_APP_ID"],
        "icon": "flip",
        "agent_action": "skill_flipbot",
    },
    "nim_router": {
        "name": "NIM Image Router",
        "description": "NVIDIA NIM image generation. FLUX.1-schnell, FLUX.1-dev, SD 3.5, visual-changenet. Pure API.",
        "category": "media",
        "needs_config": ["NIM_API_KEY"],
        "icon": "image",
        "agent_action": "skill_nim",
    },
    "daisy_chain": {
        "name": "Daisy Chain",
        "description": "Authenticated browser observer. Attaches to Chrome/Edge CDP. Watches, lints, builds living codebook.",
        "category": "browser",
        "needs_config": [],
        "icon": "browser",
        "agent_action": None,
    },
    "text_triage": {
        "name": "Text Triage",
        "description": "Auto-categorize incoming SMS, draft replies in your tone, surface what actually needs you.",
        "category": "communication",
        "needs_config": [],
        "icon": "filter",
        "agent_action": "skill_text_triage",
        "badge": "FREE",
    },
    "calendar_cleric": {
        "name": "Calendar Cleric",
        "description": "Defends your focus blocks. Reschedules low-priority meetings with a polite, on-brand note.",
        "category": "productivity",
        "needs_config": [],
        "icon": "calendar",
        "agent_action": "skill_calendar",
        "badge": None,
    },
    "receipt_rabbi": {
        "name": "Receipt Rabbi",
        "description": "Snap a receipt, get it itemized, tagged, and exported to your spreadsheet of choice.",
        "category": "finance",
        "needs_config": [],
        "icon": "receipt",
        "agent_action": "skill_receipt",
        "badge": "HOT",
    },
    "voicemail_vandal": {
        "name": "Voicemail Vandal",
        "description": "Listens to voicemails so you don't have to. Spits out a 1-line summary + suggested action.",
        "category": "communication",
        "needs_config": [],
        "icon": "voicemail",
        "agent_action": "skill_voicemail",
        "badge": "FREE",
    },
    "deal_doula": {
        "name": "Deal Doula",
        "description": "Watches the prices of things you've half-decided to buy. Pings only when it's actually a deal.",
        "category": "shopping",
        "needs_config": [],
        "icon": "pricetag",
        "agent_action": "skill_deal",
        "badge": "NEW",
    },
    "lease_lawyer": {
        "name": "Lease Lawyer",
        "description": "Reads contracts and leases. Flags weird clauses, hidden fees, and what to negotiate.",
        "category": "legal",
        "needs_config": [],
        "icon": "document",
        "agent_action": "skill_lease",
        "badge": None,
    },
    "gym_ghost": {
        "name": "Gym Ghost",
        "description": "Logs sets by voice. Builds your next workout from your last one. Zero typing.",
        "category": "health",
        "needs_config": [],
        "icon": "fitness",
        "agent_action": "skill_gym",
        "badge": None,
    },
    "dm_deflector": {
        "name": "DM Deflector",
        "description": "Filters Instagram + LinkedIn DMs. Real humans get through. Pitch decks don't.",
        "category": "communication",
        "needs_config": [],
        "icon": "shield",
        "agent_action": "skill_dm",
        "badge": "HOT",
    },
    "tab_taxidermist": {
        "name": "Tab Taxidermist",
        "description": "Closes the 84 tabs you swore you'd read. Saves the gold to a digest. Spares your RAM.",
        "category": "productivity",
        "needs_config": [],
        "icon": "browsers-outline",
        "agent_action": "skill_tabs",
        "badge": "FREE",
    },
    "fridge_forensics": {
        "name": "Fridge Forensics",
        "description": "Photo your fridge, get 3 dinner ideas using only what's already in there. No grocery run.",
        "category": "home",
        "needs_config": [],
        "icon": "restaurant-outline",
        "agent_action": "skill_fridge",
        "badge": "NEW",
    },
    "reference_bible": {
        "name": "Reference Bible",
        "description": "Local scripture lookup + meditation. No external APIs. Instant, always available.",
        "category": "reference",
        "needs_config": [],
        "icon": "book-outline",
        "agent_action": "skill_bible",
        "badge": "FREE",
    },
    "reference_dictionary": {
        "name": "Reference Dictionary",
        "description": "Fast local word definitions. Pure local knowledge, instant lookups.",
        "category": "reference",
        "needs_config": [],
        "icon": "dictionary-outline",
        "agent_action": "skill_dict",
        "badge": "FREE",
    },
    "reference_thesaurus": {
        "name": "Reference Thesaurus",
        "description": "Synonym/antonym lookup + word choice suggestion. Better communication.",
        "category": "reference",
        "needs_config": [],
        "icon": "swap-horizontal-outline",
        "agent_action": "skill_thesaurus",
        "badge": "FREE",
    },
    "problem_reverser": {
        "name": "Problem Reverser",
        "description": "Forensic diagnosis: reverse-engineer root causes from external evidence (like a detective). Outside-in analysis.",
        "category": "intelligence",
        "needs_config": [],
        "icon": "flashlight-outline",
        "agent_action": "skill_reverser",
        "badge": "NEW",
    },
    "stewardship_layer": {
        "name": "Stewardship Layer",
        "description": "Strategic governance & oversight: mission alignment, audit trails, cost management, agent drift prevention. The constitution.",
        "category": "infrastructure",
        "needs_config": [],
        "icon": "shield-checkmark-outline",
        "agent_action": "skill_steward",
        "badge": "NEW",
    },
    "stewardship_protective": {
        "name": "Stewardship (Protective)",
        "description": "Caretaker core: never destroys work without consent. Uses trash, preserves continuity, protects what matters.",
        "category": "infrastructure",
        "needs_config": [],
        "icon": "shield-lock-outline",
        "agent_action": "skill_protective",
        "badge": "CORE",
    },
    "ghidra_analyzer": {
        "name": "Ghidra Analyzer",
        "description": "Deep reverse engineering: analyze code structure, find patterns, estimate complexity, detect risks. Understand what code ACTUALLY does.",
        "category": "intelligence",
        "needs_config": [],
        "icon": "git-network-outline",
        "agent_action": "skill_ghidra",
        "badge": "NEW",
    },
    "reasoning_intentionality": {
        "name": "Intentionality Prediction",
        "description": "Level 1 Reasoning: Predicts WHY user is sending a message (question/action/learning/social/complaint/creative) before responding. Improves response relevance.",
        "category": "intelligence",
        "needs_config": [],
        "icon": "eye-outline",
        "agent_action": "skill_intent",
        "badge": "NEW",
    },
    "reasoning_temporal": {
        "name": "Temporal Reasoning",
        "description": "Level 4 Reasoning: Understands deadlines and urgency. Scores task priority as (importance × urgency) / log(deadline + 1). Prevents treating everything as equal.",
        "category": "intelligence",
        "needs_config": [],
        "icon": "timer-outline",
        "agent_action": "skill_temporal",
        "badge": "NEW",
    },
    "reasoning_cognitive_load": {
        "name": "Cognitive Load Manager",
        "description": "Level 11 Reasoning: Detects user mental bandwidth and adapts verbosity. Busy user → 1-line answers. Deep focus → full explanations. Never over-explains.",
        "category": "intelligence",
        "needs_config": [],
        "icon": "speedometer-outline",
        "agent_action": "skill_cognitive",
        "badge": "NEW",
    },
    "council": {
        "name": "Council",
        "description": "3-stage multi-model debate. Alpha/Beta/Gamma debate your question, rank each other anonymously, then a Chairman synthesizes the final verdict. No vendor bias, pure quality ranking.",
        "category": "intelligence",
        "needs_config": ["EMERGENT_LLM_KEY"],
        "icon": "business-outline",
        "agent_action": "skill_council",
        "badge": "PREMIUM",
    },
}
