// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/snowball-face/Fluid.tsx": () => import("../components/mockups/snowball-face/Fluid.tsx"),
  "./components/mockups/snowball-face/Orb.tsx": () => import("../components/mockups/snowball-face/Orb.tsx"),
  "./components/mockups/snowball-face/Pixel.tsx": () => import("../components/mockups/snowball-face/Pixel.tsx")
};
